/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-04-2017
 * 
 * XDoclet definition:
 * @struts.form name="cstCustomerForm"
 */
public class CstCustomerForm extends ActionForm {
	
	private int custLevel;//客户等级
	private int page;//跳转
	private  String lkmCustName;//姓名
    private String lkmSex;//性别
	private String lkmPostion;//职位
	private String lkmTel;//固定电话
	private String lkmMobile;//手机号码
	private String lkmMemo;//备注
	private String atvDate;//交往时间
	private String atvPlace;//地点
	private String atvTitle;//概要
	private String atvDesc;//详细信息
	private String atvRemark;//备注
	private int CustStatus;//状态
	private String lstCustManagerName;//客户经理
	private String lstCustName;//客户名称
	private int lstStatus;//状态
	
	
	private String custNo;//客户编号
	private String custManagerName;//客户经理
	private String custName;//客户名称
    private String custLevelLabel;//客户等级
	private String custRegion;//地区
	private int custSatisfy;//客户满意度
	private int custCredit;//客户信用度
	private String custAddr;//地址
	private String custZip;//邮编
	private String custTel;//电话
	private String custFax;//传真
	private String custWebsite;//网咨
	private String custLicenceNo;//营业执照号
	private String custChieftain;//法人
	private int custBankroll;//注册资金(万元)
	private int custTurnover;//年营业额
	private String custBank;//开户银行
	private String custBankAccount;//银行账号
	private String custLocalTaxNo;//地税登记号;
	private String custNationalTaxNo;//国税登记号
	
	public String getCustLevelLabel() {
		return custLevelLabel;
	}
	public void setCustLevelLabel(String custLevelLabel) {
		this.custLevelLabel = custLevelLabel;
	}
	public int getCustSatisfy() {
		return custSatisfy;
	}
	public void setCustSatisfy(int custSatisfy) {
		this.custSatisfy = custSatisfy;
	}
	public int getCustCredit() {
		return custCredit;
	}
	public void setCustCredit(int custCredit) {
		this.custCredit = custCredit;
	}
	public String getCustAddr() {
		return custAddr;
	}
	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}
	public String getCustZip() {
		return custZip;
	}
	public void setCustZip(String custZip) {
		this.custZip = custZip;
	}
	public String getCustTel() {
		return custTel;
	}
	public void setCustTel(String custTel) {
		this.custTel = custTel;
	}
	public String getCustFax() {
		return custFax;
	}
	public void setCustFax(String custFax) {
		this.custFax = custFax;
	}
	public String getCustWebsite() {
		return custWebsite;
	}
	public void setCustWebsite(String custWebsite) {
		this.custWebsite = custWebsite;
	}
	public String getCustLicenceNo() {
		return custLicenceNo;
	}
	public void setCustLicenceNo(String custLicenceNo) {
		this.custLicenceNo = custLicenceNo;
	}
	public String getCustChieftain() {
		return custChieftain;
	}
	public void setCustChieftain(String custChieftain) {
		this.custChieftain = custChieftain;
	}
	public int getCustBankroll() {
		return custBankroll;
	}
	public void setCustBankroll(int custBankroll) {
		this.custBankroll = custBankroll;
	}
	public int getCustTurnover() {
		return custTurnover;
	}
	public void setCustTurnover(int custTurnover) {
		this.custTurnover = custTurnover;
	}
	public String getCustBank() {
		return custBank;
	}
	public void setCustBank(String custBank) {
		this.custBank = custBank;
	}
	public String getCustBankAccount() {
		return custBankAccount;
	}
	public void setCustBankAccount(String custBankAccount) {
		this.custBankAccount = custBankAccount;
	}
	public String getCustLocalTaxNo() {
		return custLocalTaxNo;
	}
	public void setCustLocalTaxNo(String custLocalTaxNo) {
		this.custLocalTaxNo = custLocalTaxNo;
	}
	public String getCustNationalTaxNo() {
		return custNationalTaxNo;
	}
	public void setCustNationalTaxNo(String custNationalTaxNo) {
		this.custNationalTaxNo = custNationalTaxNo;
	}
	public int getLstStatus() {
		return lstStatus;
	}
	public void setLstStatus(int lstStatus) {
		this.lstStatus = lstStatus;
	}
	public String getLstCustManagerName() {
		return lstCustManagerName;
	}
	public void setLstCustManagerName(String lstCustManagerName) {
		this.lstCustManagerName = lstCustManagerName;
	}
	public String getLstCustName() {
		return lstCustName;
	}
	public void setLstCustName(String lstCustName) {
		this.lstCustName = lstCustName;
	}
	public int getCustStatus() {
		return CustStatus;
	}
	public void setCustStatus(int custStatus) {
		CustStatus = custStatus;
	}
	public String getAtvRemark() {
		return atvRemark;
	}
	public void setAtvRemark(String atvRemark) {
		this.atvRemark = atvRemark;
	}
	public String getAtvDate() {
		return atvDate;
	}
	public void setAtvDate(String atvDate) {
		this.atvDate = atvDate;
	}
	public String getAtvPlace() {
		return atvPlace;
	}
	public void setAtvPlace(String atvPlace) {
		this.atvPlace = atvPlace;
	}
	public String getAtvTitle() {
		return atvTitle;
	}
	public void setAtvTitle(String atvTitle) {
		this.atvTitle = atvTitle;
	}
	public String getAtvDesc() {
		return atvDesc;
	}
	public void setAtvDesc(String atvDesc) {
		this.atvDesc = atvDesc;
	}
	public String getLkmCustName() {
		return lkmCustName;
	}
	public void setLkmCustName(String lkmCustName) {
		this.lkmCustName = lkmCustName;
	}
	public String getLkmSex() {
		return lkmSex;
	}
	public void setLkmSex(String lkmSex) {
		this.lkmSex = lkmSex;
	}
	public String getLkmPostion() {
		return lkmPostion;
	}
	public void setLkmPostion(String lkmPostion) {
		this.lkmPostion = lkmPostion;
	}
	public String getLkmTel() {
		return lkmTel;
	}
	public void setLkmTel(String lkmTel) {
		this.lkmTel = lkmTel;
	}
	public String getLkmMobile() {
		return lkmMobile;
	}
	public void setLkmMobile(String lkmMobile) {
		this.lkmMobile = lkmMobile;
	}
	public String getLkmMemo() {
		return lkmMemo;
	}
	public void setLkmMemo(String lkmMemo) {
		this.lkmMemo = lkmMemo;
	}
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}
	public String getCustNo() {
		return custNo;
	}
	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}
	public String getCustManagerName() {
		return custManagerName;
	}
	public void setCustManagerName(String custManagerName) {
		this.custManagerName = custManagerName;
	}
	public int getCustLevel() {
		return custLevel;
	}
	public void setCustLevel(int custLevel) {
		this.custLevel = custLevel;
	}
	public String getCustRegion() {
		return custRegion;
	}
	public void setCustRegion(String custRegion) {
		this.custRegion = custRegion;
	}
	
}