/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.form;
import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-26-2016
 * 
 * XDoclet definition:
 * @struts.form name="productForm"
 */
public class ProductForm extends ActionForm {
	
	private String prodName;//产品名称
	private String prodType;//产品型号
	private String prodBatch;//产品批次
	public String getProdName() {
		return prodName;
	}
	public void setProdName(String prodName) {
		this.prodName = prodName;
	}
	public String getProdType() {
		return prodType;
	}
	public void setProdType(String prodType) {
		this.prodType = prodType;
	}
	public String getProdBatch() {
		return prodBatch;
	}
	public void setProdBatch(String prodBatch) {
		this.prodBatch = prodBatch;
	}
}