/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.form;

import java.util.Date;

import org.apache.struts.action.ActionForm;

import com.baidu.struts.entity.SalChance;

/** 
 * MyEclipse Struts
 * Creation date: 12-22-2016
 * 
 * XDoclet definition:
 * @struts.form name="saleChanceForm"
 */
public class SaleChanceForm extends ActionForm {
	private Integer page;
	private String chcCustName;
	private String chcLinkman;
	private String chcDesc;
	private String chcSource;
	private int  chcRate;
	private String chcTel;
	private String chcTitle;
    private int chcStatus;
	
	public int getChcStatus() {
		return chcStatus;
	}
	public void setChcStatus(int chcStatus) {
		this.chcStatus = chcStatus;
	}
	public Integer getPage() {
		return page;
	}
	public void setPage(Integer page) {
		this.page = page;
	}
	public String getChcCustName() {
		return chcCustName;
	}
	public void setChcCustName(String chcCustName) {
		this.chcCustName = chcCustName;
	}
	public String getChcLinkman() {
		return chcLinkman;
	}
	public void setChcLinkman(String chcLinkman) {
		this.chcLinkman = chcLinkman;
	}
	public String getChcDesc() {
		return chcDesc;
	}
	public void setChcDesc(String chcDesc) {
		this.chcDesc = chcDesc;
	}
	public String getChcSource() {
		return chcSource;
	}
	public void setChcSource(String chcSource) {
		this.chcSource = chcSource;
	}
	
	public int getChcRate() {
		return chcRate;
	}
	public void setChcRate(int chcRate) {
		this.chcRate = chcRate;
	}
	public String getChcTel() {
		return chcTel;
	}
	public void setChcTel(String chcTel) {
		this.chcTel = chcTel;
	}
	public String getChcTitle() {
		return chcTitle;
	}
	public void setChcTitle(String chcTitle) {
		this.chcTitle = chcTitle;
	}
}