/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.form;

import java.util.Date;
import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-28-2016
 * 
 * XDoclet definition:
 * @struts.form name="salPlanForm"
 */
public class SalPlanForm extends ActionForm {
	
	
	private  String chcCustName;//客户名称
	private String chcLinkman;//联系人
	private String chcTitle;//概要
	private String chcStatus;//状态
	private String  datetime;//日期
	private String todo;//计划项
	private int page;
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public String getDatetime() {
		return datetime;
	}
	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}
	public String getTodo() {
		return todo;
	}
	public void setTodo(String todo) {
		this.todo = todo;
	}
	public String getChcStatus() {
		return chcStatus;
	}
	public void setChcStatus(String chcStatus) {
		this.chcStatus = chcStatus;
	}
	public String getChcCustName() {
		return chcCustName;
	}
	public void setChcCustName(String chcCustName) {
		this.chcCustName = chcCustName;
	}
	public String getChcLinkman() {
		return chcLinkman;
	}
	public void setChcLinkman(String chcLinkman) {
		this.chcLinkman = chcLinkman;
	}
	public String getChcTitle() {
		return chcTitle;
	}
	public void setChcTitle(String chcTitle) {
		this.chcTitle = chcTitle;
	}
	
}