/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.form;
import org.apache.struts.action.ActionForm;
/** 
 * MyEclipse Struts
 * Creation date: 12-26-2016
 * 
 * XDoclet definition:
 * @struts.form name="storageForm"
 */
public class StorageForm extends ActionForm {
	
	private String proName;//产品名称
	private String stkWarehouse;//仓库地点
	public String getProName() {
		return proName;
	}
	public void setProName(String proName) {
		this.proName = proName;
	}
	public String getStkWarehouse() {
		return stkWarehouse;
	}
	public void setStkWarehouse(String stkWarehouse) {
		this.stkWarehouse = stkWarehouse;
	}
}