/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.form;

import org.apache.struts.action.ActionForm;

import com.baidu.struts.entity.SysUser;

/** 
 * MyEclipse Struts
 * Creation date: 12-21-2016
 * 
 * XDoclet definition:
 * @struts.form name="sysUserForm"
 */
public class SysUserForm extends ActionForm {
	
	private SysUser sysUser=new SysUser();

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}
	public SysUser getSysUser() {
		return sysUser;
	}
}