/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.action;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.baidu.biz.CstlostBiz;
import com.baidu.struts.entity.CstLost;
import com.baidu.struts.form.CstCustomerForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-10-2017
 * 
 * XDoclet definition:
 * @struts.action path="/cstlost" name="cstCustomerForm" parameter="type" scope="request" validate="true"
 */
public class CstlostAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
      private CstlostBiz cstlostBiz;
	
	public void setCstlostBiz(CstlostBiz cstlostBiz) {
		this.cstlostBiz = cstlostBiz;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 *///分页查询
	public ActionForward query(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CstCustomerForm cstCustomerForm = (CstCustomerForm) form;// TODO Auto-generated method stub
		int curPage=1;
		int pageSize=2;
		if(request.getParameter("curPage")!=null){
			curPage=Integer.parseInt(request.getParameter("curPage"));
		}
		if(curPage<1){
			curPage=1;
		}
		int maxPage=cstlostBiz.getMapg(pageSize, cstCustomerForm);
		int page=cstlostBiz.page(cstCustomerForm);
		if(curPage>maxPage && maxPage!=0){
			curPage=maxPage;
		}
		List<CstLost>list=cstlostBiz.CLost(pageSize, curPage, cstCustomerForm);
		request.getSession().setAttribute("page", page);
		request.getSession().setAttribute("maxPage", maxPage);
		request.getSession().setAttribute("list", list);
		request.getSession().setAttribute("curPage", curPage);
		return new ActionForward("/Customer/LostsPage.jsp", true);
	}//查看
	public ActionForward ue(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	  int lstId=Integer.parseInt(request.getParameter("lstId"));
	  CstLost cs=cstlostBiz.CuLost(lstId);
	  request.getSession().setAttribute("cs", cs);
	 return new ActionForward("/Customer/LostLook.jsp", true);
	}//确定流失查询
	public ActionForward AC(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int lstId=Integer.parseInt(request.getParameter("lstId"));
		CstLost cs=cstlostBiz.CuLost(lstId);
		
		 request.getSession().setAttribute("cs", cs);
		 return new ActionForward("/Customer/LostEnter.jsp", true);
	}//确认流失
	public ActionForward AW(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws ParseException {
	  String lstReason= request.getParameter("AW");
	  CstLost cc=(CstLost) request.getSession().getAttribute("cs");
	  String  date=  (String) request.getSession().getAttribute("datetime");
	  SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
	  cc.setLstReason(lstReason);
	  cc.setLstStatus("3");
	  cc.setLstLostDate(sdf.parse(date));
	  int cw=cstlostBiz.AddCstLost(cc);
	  if(cw>0){
		  return new ActionForward("/cstlost.do?type=query", true);
				  
	  }
		return null;
	}//暂缓流失查询
	public ActionForward Ad(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	
		int lstId=Integer.parseInt(request.getParameter("lstId"));
		CstLost cs=cstlostBiz.CuLost(lstId);
		 request.getSession().setAttribute("cs", cs);
		 return new ActionForward("/Customer/LostPause.jsp", true);
	}//暂缓流失
	public ActionForward Ag(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CstLost cc=(CstLost)request.getSession().getAttribute("cs");
		String lstReason=request.getParameter("cw");
		String name=cc.getLstDelay();
	   cc.setLstDelay(name+"<br/>"+lstReason+"<br/>"); 
	 int cA=cstlostBiz.updateCstLost(cc);
	 if(cA>0){
		 return new ActionForward("/cstlost.do?type=query", true); 
	 }
		return null;
	}
}