/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.baidu.biz.OrderBiz;
import com.baidu.struts.entity.CstCustomer;
import com.baidu.struts.entity.CstLost;
import com.baidu.struts.entity.OrdersLine;

/**
 * MyEclipse Struts Creation date: 12-27-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag"
 */
public class OrderAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private OrderBiz orderBiz;
	public void setOrderBiz(OrderBiz orderBiz) {
		this.orderBiz = orderBiz;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward findAllOrders(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String year=request.getParameter("Year");
		System.out.println(year);
		String cusName=request.getParameter("cusName");
		System.out.println("客户姓名："+cusName);
		List<OrdersLine> listOrders = orderBiz.findAllOrders(cusName,year);
		request.getSession().setAttribute("listOrders", listOrders);
		return new ActionForward("/Report/ContributeReport.jsp", true);
	}
	public ActionForward findAllCustomer(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取相应的值
		String type=request.getParameter("type");
		System.out.println(type);
		List<CstCustomer> list=orderBiz.find(type);
		//System.out.println(list.size());
		request.getSession().setAttribute("list", list);
		return new ActionForward("/Report/MakeReport.jsp",true);
	}
	public ActionForward findAllcstLost(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String cusName=request.getParameter("lstCustName");
		String managerName=request.getParameter("lstCustManagerName");
		List<CstLost> listCstLosts=orderBiz.findAllCstLosts(cusName,managerName);
		request.getSession().setAttribute("listCstLosts", listCstLosts);
		return new ActionForward("/Report/LostReport.jsp",true);
	}
}