/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.baidu.biz.ProductBiz;
import com.baidu.struts.entity.Product;
import com.baidu.struts.form.ProductForm;

/**
 * MyEclipse Struts Creation date: 12-26-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag" scope="request" validate="true"
 */
public class ProductAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private ProductBiz productBiz;
	public void setProductBiz(ProductBiz productBiz) {
		this.productBiz = productBiz;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward findAllProduct(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		ProductForm productForm=(ProductForm)form;
		int curPage=1;
		int pageSize=2;
		if(request.getParameter("curPage")!=null){
			curPage=Integer.parseInt(request.getParameter("curPage"));
		}
		if(curPage<1){
			curPage=1;
		}
		//求出最大页数
		int maxPage=productBiz.getMaxPage(curPage,pageSize,productForm);
		if(curPage>maxPage){
			curPage=maxPage;
		}	
		/*
		 * 跳转到哪页
		 */
		int page=productBiz.getPage(productForm);
		/*
		 * 查询记录
		 */
		int count=productBiz.getCount();
		List<Product> listpProducts=productBiz.findAllProducts(curPage,pageSize,productForm);
		request.getSession().setAttribute("listpProducts", listpProducts);
		request.getSession().setAttribute("curPage", curPage);
		request.getSession().setAttribute("maxPage", maxPage);
		request.getSession().setAttribute("count", count);
		request.getSession().setAttribute("page", page);
		return new ActionForward("/Manager/ProductSelect.jsp",true);
	}
}