/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.baidu.biz.StorageBiz;
import com.baidu.struts.entity.Storage;
import com.baidu.struts.form.StorageForm;

/**
 * MyEclipse Struts Creation date: 12-26-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class StorageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private StorageBiz storageBiz;

	public void setStorageBiz(StorageBiz storageBiz) {
		this.storageBiz = storageBiz;
	}
	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward findAllStorage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		StorageForm storageForm=(StorageForm)form;
		int curPage=1;
		int pageSize=2;
		if(request.getParameter("curPage")!=null){
			curPage=Integer.parseInt(request.getParameter("curPage"));
		}
		if(curPage<1){
			curPage=1;
		}
		//求出最大页数
		int maxPage=storageBiz.getMaxPage(curPage,pageSize,storageForm);
		if(curPage>maxPage){
			curPage=maxPage;
		}
		/*
		 * 查询记录
		 */
		int count=storageBiz.getCount();
		/*
		 * 跳转到多少也
		 */
		int size=storageBiz.getSize(storageForm);
		List<Storage> liststStorages=storageBiz.findAllStorages(curPage, pageSize, storageForm);
		request.getSession().setAttribute("liststStorages", liststStorages);
		request.getSession().setAttribute("curPage", curPage);
		request.getSession().setAttribute("maxPage", maxPage);
		request.getSession().setAttribute("count", count);
		request.getSession().setAttribute("size", size);
		return new ActionForward("/Manager/DepartSelect.jsp",true);
	}
}