/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baidu.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.baidu.biz.SysUserBiz;
import com.baidu.biz.IMPL.SysUserBizIMPL;
import com.baidu.struts.entity.SysUser;
import com.baidu.struts.form.SysUserForm;
import com.ndktools.javamd5.Mademd5;

/** 
 * MyEclipse Struts
 * Creation date: 12-21-2016
 * 
 * XDoclet definition:
 * @struts.action path="/sysUser" name="sysUserForm" parameter="type" scope="request"
 */
public class SysUserAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
    private SysUserBiz SysUserBiz;
	
	public void setSysUserBiz(SysUserBizIMPL sysUserBiz) {
		SysUserBiz = sysUserBiz;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward AddUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SysUserForm sysUserForm = (SysUserForm) form;
		SysUser sysuser=sysUserForm.getSysUser();
		String  usrName=sysuser.getUsrName();
		String usrPassword=sysuser.getUsrPassword();
	
		Mademd5 md5=new Mademd5();
		String pwd2=md5.toMd5(usrPassword);
		
		sysuser=SysUserBiz.getUser(usrName, pwd2);
		if(sysuser!=null){
			int usrId=sysuser.getUsrId();
			request.getSession().setAttribute("usrName", usrName);
			request.getSession().setAttribute("usrId", usrId);
			return new ActionForward("/Main.jsp", true);
		}else{
			return new ActionForward("/login.jsp", true);  
		}
	}
	public ActionForward dateUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		    
		  request.removeAttribute("usrName");
		
		return new ActionForward("/login.jsp", true);
	}
}